//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0
use sea_orm::{ConnectOptions, Database, DatabaseConnection, DbErr};
use std::time::Duration;

pub mod prelude;

pub mod impls;
pub mod job_assignments;
pub mod jobs;
pub mod providers;
pub mod services;
pub mod workers;

pub async fn get_sea_db_connection(url: &str) -> Result<DatabaseConnection, DbErr> {
    let mut opt = ConnectOptions::new(url.to_owned());
    opt.max_connections(100)
        .min_connections(5)
        .connect_timeout(Duration::from_secs(8))
        .idle_timeout(Duration::from_secs(8))
        .max_lifetime(Duration::from_secs(8))
        .sqlx_logging(true);

    Database::connect(opt).await
}
