//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::job_assignments::Entity as JobAssignments;
pub use super::jobs::Entity as Jobs;
pub use super::providers::Entity as Providers;
pub use super::workers::Entity as Workers;
