[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
scheduler = { path = "../scheduler" }

async-trait ="0.1"
async-std = "1.12"

[dependencies.sea-orm-migration]
version = "^0.8"
