[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
common = {path = "../common"}
sea-orm = { version = "^0.8"  }
log                 = "0.4"
serde_json = "1.0"

