refresh_rate: 15 seconds
appenders:
  stdout:
    kind: console
  incoming_outgoing_call:
    kind: rolling_file
    append: false
    path: "log/incoming_outgoing_call_stats.log"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        base: 1
        count: 100
        pattern: "logs/incoming_outgoing_call_stats.{}.gz"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%3f %Z)} [{l}] [{t} - {T}] {m}{n}"

root:
  level: info
  appenders:
    - stdout

loggers:
  mbr_stats::chain_adapter:
    level: debug
    appenders:
      - stdout
      - incoming_outgoing_call

  substrate_api_client:
    level: warn
  ws:
    level: warn
  ac_node_api:
    level: warn
