//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub mod prelude;

pub mod job_assignments;
pub mod job_result_benchmarks;
pub mod job_result_http_requests;
pub mod job_result_latest_blocks;
pub mod job_result_pings;
pub mod jobs;
pub mod plans;
pub mod provider_latest_blocks;
pub mod providers;
pub mod seaql_migrations;
pub mod worker_provider_maps;
pub mod workers;
