//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::job_assignments::Entity as JobAssignments;
pub use super::job_result_benchmarks::Entity as JobResultBenchmarks;
pub use super::job_result_http_requests::Entity as JobResultHttpRequests;
pub use super::job_result_latest_blocks::Entity as JobResultLatestBlocks;
pub use super::job_result_pings::Entity as JobResultPings;
pub use super::jobs::Entity as Jobs;
pub use super::plans::Entity as Plans;
pub use super::provider_latest_blocks::Entity as ProviderLatestBlocks;
pub use super::providers::Entity as Providers;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
pub use super::worker_provider_maps::Entity as WorkerProviderMaps;
pub use super::workers::Entity as Workers;
