//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub mod prelude;

pub mod job_assignments;
pub mod job_result_benchmarks;
pub mod job_result_latest_blocks;
pub mod job_result_pings;
pub mod jobs;
pub mod plans;
pub mod providers;
pub mod worker_provider_connections;
pub mod workers;
