//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::job_assignments::Entity as JobAssignments;
pub use super::job_result_benchmarks::Entity as JobResultBenchmarks;
pub use super::job_result_latest_blocks::Entity as JobResultLatestBlocks;
pub use super::job_result_pings::Entity as JobResultPings;
pub use super::jobs::Entity as Jobs;
pub use super::plans::Entity as Plans;
pub use super::providers::Entity as Providers;
pub use super::workers::Entity as Workers;
