#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE DATABASE "$APP_DB_NAME";
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  GRANT ALL PRIVILEGES ON DATABASE "$APP_DB_NAME" TO $APP_DB_USER;

  CREATE DATABASE "$FISHERMAN_DB_NAME";
  GRANT ALL PRIVILEGES ON DATABASE "$FSIHERMAN_DB_NAME" TO $APP_DB_USER;

EOSQL



